//Name: Steven Kaing
//ID: 33155666
//Last Modified: 04/04/2024


package edu.monash.fit2099.interfaces;
import java.util.List;

/**
 * <h1>Action Capable</h1>
 * ActionCapable explicitly indicates the list of actions that can be generated by each particular class
 * @author Steven Kaing
 * @version 1.0.0
 * @since 04/04/2024
 */
public interface ActionCapable {

    /**
     * A list of actions that a certain class could process
     * @return return a list of actions that a certain class could process
     */
    public List<Action> allowableActions();

}
